// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZaP-ydJsSCDOGeAy2yORshKVXtpUbfyw',
    appId: '1:292341323563:android:57bd38d7e185e2bc86576e',
    messagingSenderId: '292341323563',
    projectId: 'signlingo-7eab0',
    databaseURL: 'https://signlingo-7eab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlingo-7eab0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8f-eW8vJguXVaTAJm8RDOYFhbDOJn3yU',
    appId: '1:292341323563:ios:c3a41aa51df4a0f086576e',
    messagingSenderId: '292341323563',
    projectId: 'signlingo-7eab0',
    databaseURL: 'https://signlingo-7eab0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'signlingo-7eab0.appspot.com',
    iosBundleId: 'com.example.signlingo',
  );
}
